export const SET_LOADING = "SET_LOADING";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";